name: item_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # icon图标
  cupertino_icons: ^1.0.2
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 弹框
  fluttertoast: ^8.2.2
  # 网络请求
  dio: ^5.3.2
  # cookie缓存
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0+1
  # 加密
  crypto: ^3.0.3
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  # 状态，路由，依赖管理
  get: ^4.6.6
  # Html与依赖 easy_refresh 冲突【稳定版】
  flutter_html: ^3.0.0-beta.2
  #  flutter_html_video: ^3.0.0-beta.2
  #  flutter_html_table: ^3.0.0-beta.2
  #   工具库
  intl: ^0.18.1
  common_utils: 2.1.0
  sp_util: 2.0.3
  # ui库
  getwidget: ^2.0.4
  # 下拉刷新
  easy_refresh: ^3.3.2+1
  # 图片预览
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\image\loading.gif
    - assets\image\info.jpg
    - assets\icon\tx.png
    - assets\icon\TIM.png
    - assets\icon\wx.png
    - assets\icon\dd.png