name: item_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 #icon图标
  flutter_screenutil: ^5.9.0 #屏幕适配
  fluttertoast: ^8.2.2 #弹框
  dio: ^5.3.2 #网络请求
  cookie_jar: ^4.0.8 # cookie缓存
  dio_cookie_manager: ^3.1.0+1
  crypto: ^3.0.3 #加密
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  fluro: ^2.0.5 # 路由管理
  infinite_grouped_list: ^1.1.2 #无限滚动列表
  # 工具库
  common_utils: 2.1.0
  sp_util: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\image\loading.gif